title: "Amir Aynede"
email: "amiraynede.gmail.com"
description: >-
  I am Amir Aynede, a Master’s student in Bioinformatics at the Department of Pharmacy and Biotechnology (FaBiT), Alma Mater Studiorum – University of Bologna, Italy. My academic background and research interests lie at the intersection of biology and computation, with a particular focus on: Computational Biology and Structural Bioinformatics, Cancer Clinical Data Bioinformatics, and Machine Learning Applications in Diseases. My work integrates data science, biological insights, and modern AI to explore complex biomedical problems, especially in the context of cancer research. You can explore a collection of my recent and ongoing projects on my GitHub page, each accompanied by detailed documentation to ensure full reproducibility. You can find all the detailed steps on my GitHub repository, including code, notebooks, reports, and automated workflows. One of my most recent and comprehensive works is a machine learning pipeline for cancer classification using histopathological images from the LC25000 dataset. The goal of this project was to automate cancer subtype classification using deep learning—addressing limitations of manual histopathology such as subjectivity and variability across human observers. The pipeline encompasses all stages of a modern AI project: data preprocessing, training a fine-tuned ResNet18 model, model evaluation using metrics like accuracy, precision, recall, and F1-score, as well as interpretability techniques such as Grad-CAM visualizations to highlight decision-relevant image regions. This project not only demonstrates the technical steps for building reproducible ML pipelines but also reflects my commitment to transparent, accessible research in biomedical informatics.
twitter_username: ""
github_username: AmirAynede
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Rome

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Amir Aynede"
  avatar : "/assets/images/IMG.jpg"
  bio    : "Master's student in Bioinformatics | University of Bologna | Interested in Computational Biology & ML in Cancer Research"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AmirAynede"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/amir-aynede-b76840169/"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0009-0009-0550-4615"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AmirAynede"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/amir-aynede-b76840169/"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0009-0009-0550-4615"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
