title: "Amir Aynede"
email: "amiraynede@gmail.com"
description: >-
  Master’s student in Bioinformatics | University of Bologna | Focused on AI in cancer research and computational biology.
twitter_username: AmirAynede
github_username: AmirAynede
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Rome

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Amir Aynede"
  avatar : "/assets/images/IMG.jpg"
  bio    : "Master's student in Bioinformatics | University of Bologna | Interested in Computational Biology & ML in Cancer Research"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AmirAynede"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/amir-aynede-b76840169/"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0009-0009-0550-4615"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AmirAynede"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/amir-aynede-b76840169/"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0009-0009-0550-4615"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "CV"
    url: /cv/
  - title: "Contact"
    url: /contact/

# Custom styles override
sass:
  style: compressed

# Add custom stylesheet
defaults:
  - scope:
      path: "assets/css"
      type: "scss"
    values:
      permalink: /assets/css/:basename:output_ext
